export const STT_LSU_TTKT = {
  STATUS_TAT_CA: 1,
  STATUS_DA_TTKT: 200,
  STATUS_CHUA_TTKT: 201
};


// STATUS THÀNH LẬP ĐOÀN
export const TLD_STT = {
  STATUS_THANH_LAP_DOAN_CHO_DUYET_TAO_MOI: 601,
  STATUS_THANH_LAP_DOAN_DA_DUOC_DUYET_TAO_MOI: 602,
  STATUS_THANH_LAP_DOAN_CHO_DUYET_DIEU_CHINH: 603,
  STATUS_THANH_LAP_DOAN_DA_DUOC_DUYET_DIEU_CHINH: 604,
  STATUS_THANH_LAP_DOAN_TW_DA_GUI_TINH: 605
};

export const LOAIHINH_TKKT = {
  STATUS_LOAI_HINH_THANH_TRA: 1,
  STATUS_LOAI_HINH_KIEM_TRA: 2,
  STATUS_LOAI_HINH_THANH_TRA_LIEN_NGANH: 3,
  STATUS_LOAI_HINH_KIEM_TRA_LIEN_NGANH: 4
};

// STATUS KE HOACH DU THAO
export const STATUS = {
  STATUS_KHDUTHAO_TW_DUYET_KH_DU_THAO: 998,
  STATUS_KHDUTHAO_TW_TAO_KH: 1000,
  STATUS_KHDUTHAO_TW_CHO_DUYET_TAO_KH: 1001,
  STATUS_KHDUTHAO_TW_DA_DUOC_DUYET_TAO_KH: 1002,
  STATUS_KHDUTHAO_TW_CHO_DUYET_DIEU_CHINH: 1003,
  STATUS_KHDUTHAO_TW_DA_DUOC_DUYET_DIEU_CHINH: 1004,
  STATUS_KHDUTHAO_TINH_CHO_DUYET_TAO_KH: 5005,
  STATUS_KHDUTHAO_TINH_DA_DUOC_DUYET_TAO_KH: 5006,
  STATUS_KHDUTHAO_TINH_CHO_TW_DUYET: 5007,
  STATUS_KHDUTHAO_TINH_TW_TU_CHOI_KH: 5008,
  STATUS_KHDUTHAO_TINH_TW_CHAP_NHAN_KH: 5009,
  STATUS_KHDUTHAO_TINH_TW_GIAO_KE_HOACH: 5010,
  STATUS_KHDUTHAO_TINH_KE_HOACH_DA_DUOC_DIEU_CHINH: 5011,
  STATUS_KHDUTHAO_TINH_XIN_DIEU_CHINH: 5012,
  STATUS_KHDUTHAO_TINH_CHO_DUYET_XIN_DIEU_CHINH: 5013,
  STATUS_KHDUTHAO_TINH_TW_TU_CHOI_DIEU_CHINH: 5014,
  STATUS_KHDUTHAO_TINH_TW_CHAP_NHAN_DIEU_CHINH: 5015,
  STATUS_TINH_DU_KIEN_CHO_DUYET: 301,
  STATUS_TINH_DU_KIEN_DA_DUOC_DUYET: 302,
  STATUS_TINH_DU_KIEN_CHO_DUYET_DIEU_CHINH: 303,
  STATUS_TINH_DU_KIEN_DA_DUOC_DUYET_DIEU_CHINH: 304,
  TEXT_STATUS_KHDUTHAO_TINH_CHO_DUYET_TAO_KH: 'Chưa duyệt tạo kế hoạch',
  TEXT_STATUS_KHDUTHAO_TINH_DA_DUOC_DUYET_TAO_KH: 'Đã duyệt tạo kế hoạch',
  TEXT_STATUS_KHDUTHAO_TINH_CHO_TW_DUYET: 'Chờ duyệt',
  TEXT_STATUS_KHDUTHAO_TINH_TW_TU_CHOI_KH: 'Từ chối kế hoạch',
  TEXT_STATUS_KHDUTHAO_TINH_TW_CHAP_NHAN_KH: 'Chấp nhận kế hoạch',
  TEXT_STATUS_KHDUTHAO_TINH_TW_GIAO_KE_HOACH: 'Trung ương giao kế hoạch',
  TEXT_STATUS_KHDUTHAO_TINH_XIN_DIEU_CHINH: 'Xin điều chỉnh kế hoạch',
  TEXT_STATUS_KHDUTHAO_TINH_TW_TU_CHOI_DIEU_CHINH: 'Từ chối điều chỉnh kế hoạch'
};

// STATUS HOẠT ĐỘNG TTKT TẠI ĐƠN VỊ ĐỐI TƯỢNG ĐƯỢC TTKT
export const STATUS_HD_TAI_DVI = {
  STATUS_CHI_TIET_HOAT_DONG_TAI_DON_VI_DANG_TIEN_HANH: 100,
  STATUS_CHI_TIET_HOAT_DONG_TAI_DON_VI_HOAN_TTKT: 101,
  STATUS_CHI_TIET_HOAT_DONG_TAI_DON_VI_DA_KET_THUC: 102
};

// DANH MỤC TÌNH TRẠNG TÀI LIỆU => DM Tinh Trang Tai Lieu Resource
// DANH MỤC PHÂN LOẠI NỘI DUNG => chỉ xem
// DANH MỤC TỈNH HUYỆN => chỉ xem
// DANH MỤC MẪU ĐƠN => DM Mau Don Resource
// DANH MỤC TỪ CHỐI TIẾP CÔNG DÂN => DM Ly Do Tu Choi Tiep CD Resource
// DANH MỤC CHỦ TRÌ PHỐI HỢP => Dm C Tri P Hop Resource
// DANH MỤC CHỨC DANH => DM Chuc Danh User Resource
// DANH MỤC LÝ DO KHÔNG THỤ LÝ TC => DM Ly Do Ko Thu Ly TC Resource
