import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'ttkt-loai-bc-linhvuc-tinh',
  templateUrl: './loai-bc-linhvuc-tinh.component.html',
  styleUrls: ['./loai-bc-linhvuc-tinh.component.scss']
})
export class LoaiBcLinhvucTinhComponent implements OnInit {
  @Input() public loaiBaoCao: any;

  constructor() { }

  // BC Mau 06
  thucHienTTKT = [
    {
      id: 1,
      noiDung: 'Số đơn vị được TTCN',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 2,
      noiDung: 'Số đơn vị được kiểm tra',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 3,
      noiDung: 'Số đơn vị được TTKT liên ngành',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
  ];
  doiTuongDong = [
    {
      id: 1,
      noiDung: 'Số LĐ chưa đóng, đóng thiếu thời gian',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 2,
      noiDung: 'Số tiền truy đóng do chưa đóng, đóng thiếu thời gian',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 3,
      noiDung: 'Số tiền lãi truy đóng do chưa đóng, đóng thiếu thời gian',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 4,
      noiDung: 'Số lao động đóng sai đối tượng, đóng thừa thời gian phải truy giảm',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 5,
      noiDung: 'Số tiền hoàn trả do đóng sai đối tượng, đóng sai thời gian',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
  ];
  mucDong = [
    {
      id: 1,
      noiDung: 'Số LĐ đóng không đúng mức quy định',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 2,
      noiDung: 'Số tiền truy đóng do đóng không đúng mức quy định',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 3,
      noiDung: 'Số tiền lãi truy đóng do đóng thiếu mức quy định',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
  ];
  phuongThucDong = [
    {
      id: 1,
      noiDung: 'Số tiền các đơn vị sử dụng lao động nợ khi có QĐ thanh tra, kiểm tra',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 2,
      noiDung: 'Số tiền nợ đóng đơn vị đã nộp trong thời gian thanh tra, kiểm tra',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 3,
      noiDung: 'Số tiền nợ đóng được đơn vị nộp  khi thực hiện kết luận thanh tra, kiểm tra',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
  ];
  bienPhapXuLy = [
    {
      id: 1,
      noiDung: 'Số đơn vị đã lập Biên bản VPHC',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 2,
      noiDung: 'Số Q.định xử phạt VPHC đã ban hành',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 3,
      noiDung: 'Số tiền xử phạt VPHC phải thu',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 4,
      noiDung: 'Số tiền xử phạt VPHC đã thu',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
    {
      id: 5,
      noiDung: 'Các biện pháp xử lý khác ... ',
      trongKy: '',
      luyKe: '',
      ghiChu: ''
    },
  ];
  // BC Mau 07
  bcMau07 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      tongSo: '',
      TTCNDong: '',
      noiBo: '',
      DVSDLD: '',
      coSoKCB: '',
      DLThuDDTriTra: '',
      lienNganh: '',
      thucHienTongSo: '',
      phanTramsoKHTongSo: '',
      thucHienTTCNDong: '',
      phanTramsoKHTTCNDong: '',
      thucHienNoiBo: '',
      phanTramsoKHNoiBo: '',
      thucHienDVSDLD: '',
      phanTramsoKHDVSDLD: '',
      thucHiencoSoKCB: '',
      phanTramsoKHcoSoKCB: '',
      thucHienDLThuDDTriTra: '',
      phanTramsoKHDLThuDDTriTra: '',
      thucHienLienNganh: '',
      phanTramsoKHLienNganh: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      tongSo: '',
      TTCNDong: '',
      noiBo: '',
      DVSDLD: '',
      coSoKCB: '',
      DLThuDDTriTra: '',
      lienNganh: '',
      thucHienTongSo: '',
      phanTramsoKHTongSo: '',
      thucHienTTCNDong: '',
      phanTramsoKHTTCNDong: '',
      thucHienNoiBo: '',
      phanTramsoKHNoiBo: '',
      thucHienDVSDLD: '',
      phanTramsoKHDVSDLD: '',
      thucHiencoSoKCB: '',
      phanTramsoKHcoSoKCB: '',
      thucHienDLThuDDTriTra: '',
      phanTramsoKHDLThuDDTriTra: '',
      thucHienLienNganh: '',
      phanTramsoKHLienNganh: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      tongSo: '',
      TTCNDong: '',
      noiBo: '',
      DVSDLD: '',
      coSoKCB: '',
      DLThuDDTriTra: '',
      lienNganh: '',
      thucHienTongSo: '',
      phanTramsoKHTongSo: '',
      thucHienTTCNDong: '',
      phanTramsoKHTTCNDong: '',
      thucHienNoiBo: '',
      phanTramsoKHNoiBo: '',
      thucHienDVSDLD: '',
      phanTramsoKHDVSDLD: '',
      thucHiencoSoKCB: '',
      phanTramsoKHcoSoKCB: '',
      thucHienDLThuDDTriTra: '',
      phanTramsoKHDLThuDDTriTra: '',
      thucHienLienNganh: '',
      phanTramsoKHLienNganh: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      tongSo: '',
      TTCNDong: '',
      noiBo: '',
      DVSDLD: '',
      coSoKCB: '',
      DLThuDDTriTra: '',
      lienNganh: '',
      thucHienTongSo: '',
      phanTramsoKHTongSo: '',
      thucHienTTCNDong: '',
      phanTramsoKHTTCNDong: '',
      thucHienNoiBo: '',
      phanTramsoKHNoiBo: '',
      thucHienDVSDLD: '',
      phanTramsoKHDVSDLD: '',
      thucHiencoSoKCB: '',
      phanTramsoKHcoSoKCB: '',
      thucHienDLThuDDTriTra: '',
      phanTramsoKHDLThuDDTriTra: '',
      thucHienLienNganh: '',
      phanTramsoKHLienNganh: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      tongSo: '',
      TTCNDong: '',
      noiBo: '',
      DVSDLD: '',
      coSoKCB: '',
      DLThuDDTriTra: '',
      lienNganh: '',
      thucHienTongSo: '',
      phanTramsoKHTongSo: '',
      thucHienTTCNDong: '',
      phanTramsoKHTTCNDong: '',
      thucHienNoiBo: '',
      phanTramsoKHNoiBo: '',
      thucHienDVSDLD: '',
      phanTramsoKHDVSDLD: '',
      thucHiencoSoKCB: '',
      phanTramsoKHcoSoKCB: '',
      thucHienDLThuDDTriTra: '',
      phanTramsoKHDLThuDDTriTra: '',
      thucHienLienNganh: '',
      phanTramsoKHLienNganh: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      tongSo: '',
      TTCNDong: '',
      noiBo: '',
      DVSDLD: '',
      coSoKCB: '',
      DLThuDDTriTra: '',
      lienNganh: '',
      thucHienTongSo: '',
      phanTramsoKHTongSo: '',
      thucHienTTCNDong: '',
      phanTramsoKHTTCNDong: '',
      thucHienNoiBo: '',
      phanTramsoKHNoiBo: '',
      thucHienDVSDLD: '',
      phanTramsoKHDVSDLD: '',
      thucHiencoSoKCB: '',
      phanTramsoKHcoSoKCB: '',
      thucHienDLThuDDTriTra: '',
      phanTramsoKHDLThuDDTriTra: '',
      thucHienLienNganh: '',
      phanTramsoKHLienNganh: ''
    },
  ];
  // BC Mau 08
  bcMau08 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaDong: '',
      soTienTruyDong: '',
      soTienLaiTruyDong: '',
      soLDDongSai: '',
      soTienHoanTra: '',
      soLDDongThieu: '',
      soTienTruyDongSoLDDongThieu: '',
      soTienLaiTruyDongLDDongThieu: '',
      soTienDongSaiPhuongThuc: '',
      soTienLaiDongSaiPhuongThuc: '',
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaDong: '',
      soTienTruyDong: '',
      soTienLaiTruyDong: '',
      soLDDongSai: '',
      soTienHoanTra: '',
      soLDDongThieu: '',
      soTienTruyDongSoLDDongThieu: '',
      soTienLaiTruyDongLDDongThieu: '',
      soTienDongSaiPhuongThuc: '',
      soTienLaiDongSaiPhuongThuc: '',
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaDong: '',
      soTienTruyDong: '',
      soTienLaiTruyDong: '',
      soLDDongSai: '',
      soTienHoanTra: '',
      soLDDongThieu: '',
      soTienTruyDongSoLDDongThieu: '',
      soTienLaiTruyDongLDDongThieu: '',
      soTienDongSaiPhuongThuc: '',
      soTienLaiDongSaiPhuongThuc: '',
    },
    {
      id: 4,
      tenTinh: '.......',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaDong: '',
      soTienTruyDong: '',
      soTienLaiTruyDong: '',
      soLDDongSai: '',
      soTienHoanTra: '',
      soLDDongThieu: '',
      soTienTruyDongSoLDDongThieu: '',
      soTienLaiTruyDongLDDongThieu: '',
      soTienDongSaiPhuongThuc: '',
      soTienLaiDongSaiPhuongThuc: '',
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaDong: '',
      soTienTruyDong: '',
      soTienLaiTruyDong: '',
      soLDDongSai: '',
      soTienHoanTra: '',
      soLDDongThieu: '',
      soTienTruyDongSoLDDongThieu: '',
      soTienLaiTruyDongLDDongThieu: '',
      soTienDongSaiPhuongThuc: '',
      soTienLaiDongSaiPhuongThuc: '',
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaDong: '',
      soTienTruyDong: '',
      soTienLaiTruyDong: '',
      soLDDongSai: '',
      soTienHoanTra: '',
      soLDDongThieu: '',
      soTienTruyDongSoLDDongThieu: '',
      soTienLaiTruyDongLDDongThieu: '',
      soTienDongSaiPhuongThuc: '',
      soTienLaiDongSaiPhuongThuc: '',
    },
  ];
  // BC Mau 09
  bcMau09 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaCapSoBHXH: '',
      soNumberBHXHChuaTraNguoiLD: '',
      soNumberBHXHGhiSaiND: '',
      soLDChuaCapTheBHYT: '',
      soTheBHYTSaiMaQuyenLoi: '',
      soTheBHYTDauHieuTrung: '',
      soTheBHYTCapSaiDT: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaCapSoBHXH: '',
      soNumberBHXHChuaTraNguoiLD: '',
      soNumberBHXHGhiSaiND: '',
      soLDChuaCapTheBHYT: '',
      soTheBHYTSaiMaQuyenLoi: '',
      soTheBHYTDauHieuTrung: '',
      soTheBHYTCapSaiDT: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaCapSoBHXH: '',
      soNumberBHXHChuaTraNguoiLD: '',
      soNumberBHXHGhiSaiND: '',
      soLDChuaCapTheBHYT: '',
      soTheBHYTSaiMaQuyenLoi: '',
      soTheBHYTDauHieuTrung: '',
      soTheBHYTCapSaiDT: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaCapSoBHXH: '',
      soNumberBHXHChuaTraNguoiLD: '',
      soNumberBHXHGhiSaiND: '',
      soLDChuaCapTheBHYT: '',
      soTheBHYTSaiMaQuyenLoi: '',
      soTheBHYTDauHieuTrung: '',
      soTheBHYTCapSaiDT: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaCapSoBHXH: '',
      soNumberBHXHChuaTraNguoiLD: '',
      soNumberBHXHGhiSaiND: '',
      soLDChuaCapTheBHYT: '',
      soTheBHYTSaiMaQuyenLoi: '',
      soTheBHYTDauHieuTrung: '',
      soTheBHYTCapSaiDT: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLDChuaCapSoBHXH: '',
      soNumberBHXHChuaTraNguoiLD: '',
      soNumberBHXHGhiSaiND: '',
      soLDChuaCapTheBHYT: '',
      soTheBHYTSaiMaQuyenLoi: '',
      soTheBHYTDauHieuTrung: '',
      soTheBHYTCapSaiDT: ''
    }
  ];
  // BC Mau 10
  bcMau10 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLuot: '',
      soTienThuHoiHuongBHXHNganHan: '',
      soLDHuongBHXHDaiHan: '',
      soTienThuHoiHuongBHXHDaiHan: '',
      soLDHuongThieuTienBHXH: '',
      soDTHuongThieuTienBHXH: '',
      soTienHoanTra: '',
      soCoSoKCBBHYT: '',
      soTienPhaiThuHoi: '',
      soTienDaThuHoi: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLuot: '',
      soTienThuHoiHuongBHXHNganHan: '',
      soLDHuongBHXHDaiHan: '',
      soTienThuHoiHuongBHXHDaiHan: '',
      soLDHuongThieuTienBHXH: '',
      soDTHuongThieuTienBHXH: '',
      soTienHoanTra: '',
      soCoSoKCBBHYT: '',
      soTienPhaiThuHoi: '',
      soTienDaThuHoi: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLuot: '',
      soTienThuHoiHuongBHXHNganHan: '',
      soLDHuongBHXHDaiHan: '',
      soTienThuHoiHuongBHXHDaiHan: '',
      soLDHuongThieuTienBHXH: '',
      soDTHuongThieuTienBHXH: '',
      soTienHoanTra: '',
      soCoSoKCBBHYT: '',
      soTienPhaiThuHoi: '',
      soTienDaThuHoi: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLuot: '',
      soTienThuHoiHuongBHXHNganHan: '',
      soLDHuongBHXHDaiHan: '',
      soTienThuHoiHuongBHXHDaiHan: '',
      soLDHuongThieuTienBHXH: '',
      soDTHuongThieuTienBHXH: '',
      soTienHoanTra: '',
      soCoSoKCBBHYT: '',
      soTienPhaiThuHoi: '',
      soTienDaThuHoi: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLuot: '',
      soTienThuHoiHuongBHXHNganHan: '',
      soLDHuongBHXHDaiHan: '',
      soTienThuHoiHuongBHXHDaiHan: '',
      soLDHuongThieuTienBHXH: '',
      soDTHuongThieuTienBHXH: '',
      soTienHoanTra: '',
      soCoSoKCBBHYT: '',
      soTienPhaiThuHoi: '',
      soTienDaThuHoi: ''
    },
    {
      id: 6,
      tenTinh: 'Tồng cộng',
      soDVTTCN: '',
      soDVKiemTra: '',
      soDVTTKTLienNganh: '',
      soLuot: '',
      soTienThuHoiHuongBHXHNganHan: '',
      soLDHuongBHXHDaiHan: '',
      soTienThuHoiHuongBHXHDaiHan: '',
      soLDHuongThieuTienBHXH: '',
      soDTHuongThieuTienBHXH: '',
      soTienHoanTra: '',
      soCoSoKCBBHYT: '',
      soTienPhaiThuHoi: '',
      soTienDaThuHoi: ''
    },
  ];
  // BC Mau 11
  bcMau11 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      soTienLaiTruyDongDaThu: '',
      phanTramSoPhaiTruyDong: '',
      soTienDaHoanTra: '',
      phanTramSoPhaiTraDaHoanTra: '',
      soTienDaThuHoiBHXH: '',
      phanTramSoPhaiThuBHXH: '',
      soTienDaHoanTraDT: '',
      phanTramSoPhaiTraDaHoanTraDT: '',
      soTienDaThuHoiBHYT: '',
      phanTramSoPhaiThuBHYT: '',
      soDonViXuPhat: '',
      soTienPhaiThu: '',
      soTienDaThu: '',
      phanTramSoPhaiThuXuPhat: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      soTienLaiTruyDongDaThu: '',
      phanTramSoPhaiTruyDong: '',
      soTienDaHoanTra: '',
      phanTramSoPhaiTraDaHoanTra: '',
      soTienDaThuHoiBHXH: '',
      phanTramSoPhaiThuBHXH: '',
      soTienDaHoanTraDT: '',
      phanTramSoPhaiTraDaHoanTraDT: '',
      soTienDaThuHoiBHYT: '',
      phanTramSoPhaiThuBHYT: '',
      soDonViXuPhat: '',
      soTienPhaiThu: '',
      soTienDaThu: '',
      phanTramSoPhaiThuXuPhat: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      soTienLaiTruyDongDaThu: '',
      phanTramSoPhaiTruyDong: '',
      soTienDaHoanTra: '',
      phanTramSoPhaiTraDaHoanTra: '',
      soTienDaThuHoiBHXH: '',
      phanTramSoPhaiThuBHXH: '',
      soTienDaHoanTraDT: '',
      phanTramSoPhaiTraDaHoanTraDT: '',
      soTienDaThuHoiBHYT: '',
      phanTramSoPhaiThuBHYT: '',
      soDonViXuPhat: '',
      soTienPhaiThu: '',
      soTienDaThu: '',
      phanTramSoPhaiThuXuPhat: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      soTienLaiTruyDongDaThu: '',
      phanTramSoPhaiTruyDong: '',
      soTienDaHoanTra: '',
      phanTramSoPhaiTraDaHoanTra: '',
      soTienDaThuHoiBHXH: '',
      phanTramSoPhaiThuBHXH: '',
      soTienDaHoanTraDT: '',
      phanTramSoPhaiTraDaHoanTraDT: '',
      soTienDaThuHoiBHYT: '',
      phanTramSoPhaiThuBHYT: '',
      soDonViXuPhat: '',
      soTienPhaiThu: '',
      soTienDaThu: '',
      phanTramSoPhaiThuXuPhat: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      soTienLaiTruyDongDaThu: '',
      phanTramSoPhaiTruyDong: '',
      soTienDaHoanTra: '',
      phanTramSoPhaiTraDaHoanTra: '',
      soTienDaThuHoiBHXH: '',
      phanTramSoPhaiThuBHXH: '',
      soTienDaHoanTraDT: '',
      phanTramSoPhaiTraDaHoanTraDT: '',
      soTienDaThuHoiBHYT: '',
      phanTramSoPhaiThuBHYT: '',
      soDonViXuPhat: '',
      soTienPhaiThu: '',
      soTienDaThu: '',
      phanTramSoPhaiThuXuPhat: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      soTienLaiTruyDongDaThu: '',
      phanTramSoPhaiTruyDong: '',
      soTienDaHoanTra: '',
      phanTramSoPhaiTraDaHoanTra: '',
      soTienDaThuHoiBHXH: '',
      phanTramSoPhaiThuBHXH: '',
      soTienDaHoanTraDT: '',
      phanTramSoPhaiTraDaHoanTraDT: '',
      soTienDaThuHoiBHYT: '',
      phanTramSoPhaiThuBHYT: '',
      soDonViXuPhat: '',
      soTienPhaiThu: '',
      soTienDaThu: '',
      phanTramSoPhaiThuXuPhat: ''
    },
  ];
  // BC Mau 12
  bcMau12 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
  ];
  // BC Mau 13
  bcMau13 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
  ];
  // BC Mau 14
  bcMau14 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      tongSo: '',
      TTCN: '',
      phanTramTTsoKH: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      tongSo: '',
      TTCN: '',
      phanTramTTsoKH: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      tongSo: '',
      TTCN: '',
      phanTramTTsoKH: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      tongSo: '',
      TTCN: '',
      phanTramTTsoKH: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      tongSo: '',
      TTCN: '',
      phanTramTTsoKH: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      tongSo: '',
      TTCN: '',
      phanTramTTsoKH: '',
      kiemTra: '',
      lienNganh: '',
      LDChuaDong: '',
      soTienTruyDongDT: '',
      LDDongSai: '',
      soTienHoanTra: '',
      LDDongKhongDungMuc: '',
      soTienTruyDongMucDong: '',
      STienDVno: '',
      soTienDaNopKhiTTKT: '',
      STDaNopKhiKL: ''
    },
  ];
  // BC Mau 15
  bcMau15 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      tongSo: '',
      TTCN: '',
      kiemTra: '',
      lienNganh: '',
      soDonVi: '',
      soQDXuPhat: '',
      soTienXuPhatPhaiThu: '',
      soTienXuPhatDaThu: '',
      bienPhapXuLy: ''
    },
  ];
  // BC Mau 16
  bcMau16 = [
    {
      id: 1,
      tenTinh: 'Hà Nội',
      soDVSDLD: '',
      soCoSoKCBBHYT: '',
      soDaiLyThuSoLieuQuanLy: '',
      TTCoQuanBHXHThucHien: '',
      coQuanBHXH: '',
      DonViSDLDCoQuanBHXH: '',
      soCoSoKCBBHYTCoQuanBHXH: '',
      daiLyThuCoQuanBHXH: '',
      TTPhoiHopLienNganh: '',
      DonViSDLDLienNganh: '',
      soCoSoKCBLienNganh: ''
    },
    {
      id: 2,
      tenTinh: 'Đà Nẵng',
      soDVSDLD: '',
      soCoSoKCBBHYT: '',
      soDaiLyThuSoLieuQuanLy: '',
      TTCoQuanBHXHThucHien: '',
      coQuanBHXH: '',
      DonViSDLDCoQuanBHXH: '',
      soCoSoKCBBHYTCoQuanBHXH: '',
      daiLyThuCoQuanBHXH: '',
      TTPhoiHopLienNganh: '',
      DonViSDLDLienNganh: '',
      soCoSoKCBLienNganh: ''
    },
    {
      id: 3,
      tenTinh: 'Hồ Chí Minh',
      soDVSDLD: '',
      soCoSoKCBBHYT: '',
      soDaiLyThuSoLieuQuanLy: '',
      TTCoQuanBHXHThucHien: '',
      coQuanBHXH: '',
      DonViSDLDCoQuanBHXH: '',
      soCoSoKCBBHYTCoQuanBHXH: '',
      daiLyThuCoQuanBHXH: '',
      TTPhoiHopLienNganh: '',
      DonViSDLDLienNganh: '',
      soCoSoKCBLienNganh: ''
    },
    {
      id: 4,
      tenTinh: '.......',
      soDVSDLD: '',
      soCoSoKCBBHYT: '',
      soDaiLyThuSoLieuQuanLy: '',
      TTCoQuanBHXHThucHien: '',
      coQuanBHXH: '',
      DonViSDLDCoQuanBHXH: '',
      soCoSoKCBBHYTCoQuanBHXH: '',
      daiLyThuCoQuanBHXH: '',
      TTPhoiHopLienNganh: '',
      DonViSDLDLienNganh: '',
      soCoSoKCBLienNganh: ''
    },
    {
      id: 5,
      tenTinh: 'Vụ TTKT',
      soDVSDLD: '',
      soCoSoKCBBHYT: '',
      soDaiLyThuSoLieuQuanLy: '',
      TTCoQuanBHXHThucHien: '',
      coQuanBHXH: '',
      DonViSDLDCoQuanBHXH: '',
      soCoSoKCBBHYTCoQuanBHXH: '',
      daiLyThuCoQuanBHXH: '',
      TTPhoiHopLienNganh: '',
      DonViSDLDLienNganh: '',
      soCoSoKCBLienNganh: ''
    },
    {
      id: 6,
      tenTinh: 'Tổng cộng',
      soDVSDLD: '',
      soCoSoKCBBHYT: '',
      soDaiLyThuSoLieuQuanLy: '',
      TTCoQuanBHXHThucHien: '',
      coQuanBHXH: '',
      DonViSDLDCoQuanBHXH: '',
      soCoSoKCBBHYTCoQuanBHXH: '',
      daiLyThuCoQuanBHXH: '',
      TTPhoiHopLienNganh: '',
      DonViSDLDLienNganh: '',
      soCoSoKCBLienNganh: ''
    },
  ];

  ngOnInit() {
  }

}
